version: '3.8'

services:
  mysql_contactos:
    image: mysql:8.0
    container_name: leasein_mysql_contactos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contactos_db
      MYSQL_USER: leasein_user
      MYSQL_PASSWORD: leasein_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: